nodes:
  context: {}
  window:
    properties:
      source: {}
      external-id: {}
  workspace:
    properties:
      source: {}
      external-id: {}
      idx: {}
      name: {}
      active: {}
      focused: {}
      urgent: {}
  project:
    properties:
      path:
        required: true
      name: {}
      icon: {}
  agent-session:
    properties:
      id: {}
      cwd: {}
      model: {}
  app-instance:
    properties:
      name: {}
      icon: {}
  output:
    properties:
      source: {}
      connector: {}

relations:
  window:
    from:
      exact: context:selected
    to: window
    cardinality: many-to-one

  workspace:
    from: any
    to: workspace
    cardinality: many-to-one

  output:
    from: workspace
    to: output
    cardinality: many-to-one

  project:
    from: workspace
    to: project
    cardinality: many-to-one
    retention: static

  session-project:
    from: agent-session
    to: project
    cardinality: many-to-one

  agent-session:
    from: app-instance
    to: agent-session
    cardinality: one-to-one
    retention: weak

  app-instance:
    from: window
    to: app-instance
    cardinality: one-to-one
    retention: weak

paths:
  selected-window:
    from: context:selected
    path: [window]

  selected-workspace:
    from: context:selected
    path: [workspace]

  selected-output:
    from: context:selected
    path: [workspace, output]

  selected-project:
    from: context:selected
    path: [workspace, project]

  selected-agent-session:
    from: context:selected
    path: [window, app-instance, agent-session]

  agent-session-workspace:
    from: agent-session
    path: [agent-session, app-instance, workspace]

  agent-session-project:
    from: agent-session
    path: [session-project]

  window-agent-session:
    from: window
    path: [app-instance, agent-session]
