nodes:
  context: {}
  window:
    properties:
      source: {}
      external-id: {}
  workspace:
    properties:
      source: {}
      external-id: {}
      idx: {}
      name: {}
      active: {}
      focused: {}
      urgent: {}
  project:
    properties:
      path:
        required: true
      name: {}
      icon: {}
  agent-session:
    properties:
      cwd: {}
      model: {}
  output:
    properties:
      source: {}
      connector: {}

relations:
  window:
    from:
      exact: context:selected
    to: window
    cardinality: many-to-one

  workspace:
    from: window
    to: workspace
    cardinality: many-to-one

  selected-workspace:
    from:
      exact: context:selected
    to: workspace
    cardinality: many-to-one

  output:
    from: workspace
    to: output
    cardinality: many-to-one

  project:
    from: workspace
    to: project
    cardinality: one-to-one

  agent-session:
    from: window
    to: agent-session
    cardinality: one-to-one

paths:
  selected-window:
    from: context:selected
    path: [window]

  selected-workspace:
    from: context:selected
    path: [selected-workspace]

  selected-output:
    from: context:selected
    path: [selected-workspace, output]

  selected-project:
    from: context:selected
    path: [selected-workspace, project]

  selected-agent-session:
    from: context:selected
    path: [window, agent-session]
