use std::fmt::Write as _;
use std::path::PathBuf;

use anyhow::Context;
use clap::Parser;
use locus_schema::{Cardinality, GraphSchema, NodeSelector};

#[derive(Debug, Parser)]
#[command(name = "locus-codegen")]
#[command(about = "Generate TypeScript helpers from a Locus schema")]
struct Args {
    #[arg(long, default_value = "schema.yaml")]
    schema: PathBuf,
    #[arg(long)]
    out: Option<PathBuf>,
}

fn main() -> anyhow::Result<()> {
    let args = Args::parse();
    let schema = GraphSchema::load(&args.schema)
        .with_context(|| format!("load schema {}", args.schema.display()))?;
    let output = generate_typescript(&schema);

    if let Some(out) = args.out {
        std::fs::write(&out, output).with_context(|| format!("write {}", out.display()))?;
    } else {
        print!("{output}");
    }

    Ok(())
}

fn generate_typescript(schema: &GraphSchema) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "/* eslint-disable */\n// Generated by locus-codegen. Do not edit by hand.\n"
    )
    .unwrap();

    write_string_union(
        &mut out,
        "NodeKind",
        schema.nodes().keys().map(String::as_str),
    );
    write_string_union(
        &mut out,
        "Relation",
        schema.relations().keys().map(String::as_str),
    );
    write_string_union(
        &mut out,
        "NamedPath",
        schema.paths().keys().map(String::as_str),
    );

    writeln!(
        out,
        "export type NodeId = string;\nexport type OptionalNodeId = NodeId | null;\n"
    )
    .unwrap();

    writeln!(
        out,
        "export type NodeSelector =\n  | {{ type: \"any\" }}\n  | {{ type: \"kind\"; kind: NodeKind | string }}\n  | {{ type: \"exact\"; id: NodeId }};\n"
    )
    .unwrap();

    writeln!(out, "export const locusSchema = {{").unwrap();
    write_nodes(&mut out, schema);
    write_relations(&mut out, schema);
    write_paths(&mut out, schema);
    writeln!(out, "}} as const;\n").unwrap();

    writeln!(
        out,
        "export interface LocusDbusClient {{\n  setLink(source: string, relation: string, target: string): Promise<void>;\n  removeLink(source: string, relation: string, target: string): Promise<void>;\n  getTargets(source: string, relation: string): Promise<string[]>;\n  getSources(target: string, relation: string): Promise<string[]>;\n  setProperty(subject: string, key: string, value: string): Promise<void>;\n  getProperty(subject: string, key: string): Promise<string>;\n  getProperties(subject: string): Promise<Record<string, string>>;\n  resolve(source: string, path: string[]): Promise<string>;\n  resolveAll(source: string, path: string[]): Promise<string[]>;\n  subscribeResolve(source: string, path: string[]): Promise<string>;\n}}\n"
    )
    .unwrap();

    writeln!(
        out,
        "function none(value: string): OptionalNodeId {{\n  return value.length === 0 ? null : value;\n}}\n"
    )
    .unwrap();

    writeln!(
        out,
        "export class LocusSchemaClient {{\n  constructor(private readonly client: LocusDbusClient) {{}}\n\n  setRelation(source: NodeId, relation: Relation, target: NodeId): Promise<void> {{\n    return this.client.setLink(source, relation, target);\n  }}\n\n  removeRelation(source: NodeId, relation: Relation, target: NodeId): Promise<void> {{\n    return this.client.removeLink(source, relation, target);\n  }}\n\n  targets(source: NodeId, relation: Relation): Promise<NodeId[]> {{\n    return this.client.getTargets(source, relation);\n  }}\n\n  sources(target: NodeId, relation: Relation): Promise<NodeId[]> {{\n    return this.client.getSources(target, relation);\n  }}\n\n  setProperty(subject: NodeId, key: string, value: string): Promise<void> {{\n    return this.client.setProperty(subject, key, value);\n  }}\n\n  async property(subject: NodeId, key: string): Promise<string | null> {{\n    return none(await this.client.getProperty(subject, key));\n  }}\n\n  properties(subject: NodeId): Promise<Record<string, string>> {{\n    return this.client.getProperties(subject);\n  }}\n\n  async resolvePath(name: NamedPath): Promise<OptionalNodeId> {{\n    const spec = locusSchema.paths[name];\n    return none(await this.client.resolve(spec.from, [...spec.path]));\n  }}\n\n  resolveAllPath(name: NamedPath): Promise<NodeId[]> {{\n    const spec = locusSchema.paths[name];\n    return this.client.resolveAll(spec.from, [...spec.path]);\n  }}\n\n  async subscribePath(name: NamedPath): Promise<OptionalNodeId> {{\n    const spec = locusSchema.paths[name];\n    return none(await this.client.subscribeResolve(spec.from, [...spec.path]));\n  }}\n"
    )
    .unwrap();

    for path_name in schema.paths().keys() {
        let method = camel_ident(path_name);
        writeln!(
            out,
            "  {method}(): Promise<OptionalNodeId> {{\n    return this.resolvePath({path:?});\n  }}\n\n  subscribe{upper_method}(): Promise<OptionalNodeId> {{\n    return this.subscribePath({path:?});\n  }}\n",
            method = method,
            upper_method = upper_first(&method),
            path = path_name,
        )
        .unwrap();
    }

    writeln!(out, "}}\n").unwrap();
    out
}

fn write_string_union<'a>(out: &mut String, name: &str, values: impl Iterator<Item = &'a str>) {
    let values = values.collect::<Vec<_>>();
    if values.is_empty() {
        writeln!(out, "export type {name} = never;\n").unwrap();
        return;
    }

    writeln!(out, "export type {name} =").unwrap();
    for value in values {
        writeln!(out, "  | {value:?}").unwrap();
    }
    writeln!(out, ";\n").unwrap();
}

fn write_nodes(out: &mut String, schema: &GraphSchema) {
    writeln!(out, "  nodes: {{").unwrap();
    for (kind, node) in schema.nodes() {
        writeln!(out, "    {kind:?}: {{").unwrap();
        writeln!(out, "      properties: {{").unwrap();
        for (property, spec) in &node.properties {
            writeln!(
                out,
                "        {property:?}: {{ required: {required} }},",
                required = spec.required
            )
            .unwrap();
        }
        writeln!(out, "      }},").unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "  }},").unwrap();
}

fn write_relations(out: &mut String, schema: &GraphSchema) {
    writeln!(out, "  relations: {{").unwrap();
    for (name, relation) in schema.relations() {
        writeln!(out, "    {name:?}: {{").unwrap();
        writeln!(out, "      from: {},", selector_ts(&relation.source)).unwrap();
        writeln!(out, "      to: {},", selector_ts(&relation.target)).unwrap();
        writeln!(
            out,
            "      cardinality: {cardinality:?},",
            cardinality =
                cardinality_name(relation.sources_per_target, relation.targets_per_source)
        )
        .unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "  }},").unwrap();
}

fn write_paths(out: &mut String, schema: &GraphSchema) {
    writeln!(out, "  paths: {{").unwrap();
    for (name, path) in schema.paths() {
        writeln!(out, "    {name:?}: {{").unwrap();
        writeln!(out, "      from: {:?},", path.source).unwrap();
        write!(out, "      path: [").unwrap();
        for (index, relation) in path.path.iter().enumerate() {
            if index > 0 {
                write!(out, ", ").unwrap();
            }
            write!(out, "{relation:?}").unwrap();
        }
        writeln!(out, "],").unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "  }},").unwrap();
}

fn selector_ts(selector: &NodeSelector) -> String {
    match selector {
        NodeSelector::Any => "{ type: \"any\" }".to_string(),
        NodeSelector::Kind(kind) => format!("{{ type: \"kind\", kind: {kind:?} }}"),
        NodeSelector::Exact(id) => format!("{{ type: \"exact\", id: {id:?} }}"),
    }
}

fn cardinality_name(
    sources_per_target: Cardinality,
    targets_per_source: Cardinality,
) -> &'static str {
    match (sources_per_target, targets_per_source) {
        (Cardinality::One, Cardinality::One) => "one-to-one",
        (Cardinality::Many, Cardinality::One) => "many-to-one",
        (Cardinality::One, Cardinality::Many) => "one-to-many",
        (Cardinality::Many, Cardinality::Many) => "many-to-many",
    }
}

fn camel_ident(value: &str) -> String {
    let mut out = String::new();
    let mut uppercase_next = false;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            if out.is_empty() {
                out.push(ch.to_ascii_lowercase());
            } else if uppercase_next {
                out.push(ch.to_ascii_uppercase());
                uppercase_next = false;
            } else {
                out.push(ch);
            }
        } else {
            uppercase_next = true;
        }
    }
    if out.is_empty() || out.as_bytes()[0].is_ascii_digit() {
        out.insert(0, '_');
    }
    out
}

fn upper_first(value: &str) -> String {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return String::new();
    };
    format!("{}{}", first.to_ascii_uppercase(), chars.as_str())
}
