use std::io::Write;

use anyhow::{Result, bail};
use locus_schema::{GraphSchema, NodeSelector};

use crate::args::Adapter;
use crate::producer::CodeProducer;

pub struct ShellProducer {
    adapter: Option<Adapter>,
}

impl ShellProducer {
    pub fn new(adapter: Option<Adapter>) -> Self {
        Self { adapter }
    }
}

impl CodeProducer for ShellProducer {
    fn language(&self) -> &'static str {
        "shell"
    }

    fn file_extension(&self) -> &'static str {
        "sh"
    }

    fn generate(&self, schema: &GraphSchema, out: &mut dyn Write) -> Result<()> {
        if self.adapter.is_some() {
            bail!("shell output does not support adapters");
        }
        generate_shell(schema, out)?;
        Ok(())
    }
}

fn generate_shell(schema: &GraphSchema, out: &mut dyn Write) -> std::io::Result<()> {
    writeln!(out, "# Generated by locus-codegen. Do not edit by hand.")?;
    writeln!(out, "# Source this file from bash or zsh.")?;
    writeln!(out)?;
    writeln!(out, ": \"${{LOCUSCTL:=locusctl}}\"")?;
    writeln!(out)?;

    write_base_functions(out)?;
    for (name, path) in schema.paths() {
        write_path_functions(out, schema, name, path)?;
    }
    Ok(())
}

fn write_base_functions(out: &mut dyn Write) -> std::io::Result<()> {
    out.write_all(include_str!("base.sh").as_bytes())
}

fn write_path_functions(
    out: &mut dyn Write,
    schema: &GraphSchema,
    name: &str,
    path: &locus_schema::PathSpec,
) -> std::io::Result<()> {
    let function = format!("locus_{}", shell_name(name));
    let source_arg = schema.nodes().contains_key(&path.source);
    let path_args = path
        .path
        .iter()
        .map(|relation| shell_quote(relation))
        .collect::<Vec<_>>()
        .join(" ");

    if source_arg {
        writeln!(out, "{function}() {{")?;
        writeln!(out, "  local source=\"${{1:?usage: {function} <source>}}\"")?;
        writeln!(out, "  \"$LOCUSCTL\" resolve \"$source\" {path_args}")?;
        writeln!(out, "}}\n")?;

        writeln!(out, "{function}_all() {{")?;
        writeln!(
            out,
            "  local source=\"${{1:?usage: {function}_all <source>}}\""
        )?;
        writeln!(out, "  \"$LOCUSCTL\" resolve-all \"$source\" {path_args}")?;
        writeln!(out, "}}\n")?;

        writeln!(out, "{function}_prop() {{")?;
        writeln!(
            out,
            "  local source=\"${{1:?usage: {function}_prop <source> <key>}}\""
        )?;
        writeln!(
            out,
            "  local key=\"${{2:?usage: {function}_prop <source> <key>}}\""
        )?;
        writeln!(out, "  local subject")?;
        writeln!(
            out,
            "  subject=$(\"$LOCUSCTL\" resolve \"$source\" {path_args}) || return"
        )?;
        writeln!(out, "  [ -n \"$subject\" ] || return 1")?;
        writeln!(out, "  \"$LOCUSCTL\" prop get \"$subject\" \"$key\"")?;
        writeln!(out, "}}\n")?;

        writeln!(out, "{function}_props() {{")?;
        writeln!(
            out,
            "  local source=\"${{1:?usage: {function}_props <source>}}\""
        )?;
        writeln!(out, "  local subject")?;
        writeln!(
            out,
            "  subject=$(\"$LOCUSCTL\" resolve \"$source\" {path_args}) || return"
        )?;
        writeln!(out, "  [ -n \"$subject\" ] || return 1")?;
        writeln!(out, "  \"$LOCUSCTL\" prop list \"$subject\"")?;
        writeln!(out, "}}\n")?;
    } else {
        let source = shell_quote(&path.source);
        writeln!(out, "{function}() {{")?;
        writeln!(out, "  \"$LOCUSCTL\" resolve {source} {path_args}")?;
        writeln!(out, "}}\n")?;

        writeln!(out, "{function}_all() {{")?;
        writeln!(out, "  \"$LOCUSCTL\" resolve-all {source} {path_args}")?;
        writeln!(out, "}}\n")?;

        writeln!(out, "{function}_prop() {{")?;
        writeln!(out, "  local key=\"${{1:?usage: {function}_prop <key>}}\"")?;
        writeln!(out, "  local subject")?;
        writeln!(out, "  subject=$({function}) || return")?;
        writeln!(out, "  [ -n \"$subject\" ] || return 1")?;
        writeln!(out, "  \"$LOCUSCTL\" prop get \"$subject\" \"$key\"")?;
        writeln!(out, "}}\n")?;

        writeln!(out, "{function}_props() {{")?;
        writeln!(out, "  local subject")?;
        writeln!(out, "  subject=$({function}) || return")?;
        writeln!(out, "  [ -n \"$subject\" ] || return 1")?;
        writeln!(out, "  \"$LOCUSCTL\" prop list \"$subject\"")?;
        writeln!(out, "}}\n")?;
    }

    if let Some(kind) = path_target_kind(schema, path) {
        if let Some(node) = schema.nodes().get(kind) {
            for property in node.properties.keys() {
                let property_function = format!("{function}_{}", shell_name(property));
                if source_arg {
                    writeln!(out, "{property_function}() {{")?;
                    writeln!(out, "  {function}_prop \"$1\" {}", shell_quote(property))?;
                    writeln!(out, "}}\n")?;
                } else {
                    writeln!(out, "{property_function}() {{")?;
                    writeln!(out, "  {function}_prop {}", shell_quote(property))?;
                    writeln!(out, "}}\n")?;
                }
            }
        }
    }

    Ok(())
}

fn path_target_kind<'a>(
    schema: &'a GraphSchema,
    path: &'a locus_schema::PathSpec,
) -> Option<&'a str> {
    let mut kind = schema
        .nodes()
        .contains_key(&path.source)
        .then_some(path.source.as_str());
    for relation in &path.path {
        let relation = schema.relations().get(relation)?;
        kind = match &relation.target {
            NodeSelector::Kind(kind) => Some(kind.as_str()),
            _ => None,
        };
    }
    kind
}

fn shell_name(name: &str) -> String {
    let mut output = String::new();
    let mut last_was_separator = false;
    for character in name.chars() {
        if character.is_ascii_alphanumeric() {
            output.push(character.to_ascii_lowercase());
            last_was_separator = false;
        } else if !last_was_separator && !output.is_empty() {
            output.push('_');
            last_was_separator = true;
        }
    }
    while output.ends_with('_') {
        output.pop();
    }
    if output
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_alphabetic() || character == '_')
    {
        output
    } else if output.is_empty() {
        "path".to_string()
    } else {
        format!("path_{output}")
    }
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}
