use std::io::Write;

use anyhow::Result;
use locus_schema::{Cardinality, GraphSchema, NodeSelector};

use crate::args::Adapter;
use crate::producer::CodeProducer;

pub struct TypeScriptProducer {
    adapter: Option<Adapter>,
}

impl TypeScriptProducer {
    pub fn new(adapter: Option<Adapter>) -> Self {
        Self { adapter }
    }
}

impl CodeProducer for TypeScriptProducer {
    fn language(&self) -> &'static str {
        "ts"
    }

    fn file_extension(&self) -> &'static str {
        "ts"
    }

    fn generate(&self, schema: &GraphSchema, out: &mut dyn Write) -> Result<()> {
        generate_typescript(schema, out, self.adapter)?;
        Ok(())
    }
}

fn generate_typescript(
    schema: &GraphSchema,
    out: &mut dyn Write,
    adapter: Option<Adapter>,
) -> std::io::Result<()> {
    writeln!(
        out,
        "/* eslint-disable */\n// Generated by locus-codegen. Do not edit by hand.\n\nimport Gio from 'gi://Gio?version=2.0';\nimport GLib from 'gi://GLib?version=2.0';\n"
    )?;
    if matches!(adapter, Some(Adapter::Rx)) {
        writeln!(
            out,
            "import {{ Observable, distinctUntilChanged, map, shareReplay, switchMap }} from 'rxjs';\n"
        )?;
    }

    write_string_union(out, "NodeKind", schema.nodes().keys().map(String::as_str))?;
    write_string_union(
        out,
        "Relation",
        schema.relations().keys().map(String::as_str),
    )?;
    write_string_union(out, "NamedPath", schema.paths().keys().map(String::as_str))?;

    writeln!(
        out,
        "export type NodeId = string;\nexport type OptionalNodeId = NodeId | null;\nexport type Unsubscribe = () => void;\n"
    )?;

    writeln!(
        out,
        "export type NodeSelector =\n  | {{ type: \"any\" }}\n  | {{ type: \"kind\"; kind: NodeKind | string }}\n  | {{ type: \"exact\"; id: NodeId }};\n"
    )?;

    writeln!(out, "export const locusSchema = {{")?;
    write_nodes(out, schema)?;
    write_relations(out, schema)?;
    write_paths(out, schema)?;
    writeln!(out, "}} as const;\n")?;

    write_property_types(out, schema)?;
    write_dbus_client(out)?;
    if matches!(adapter, Some(Adapter::Rx)) {
        write_rx_adapter(out, schema)?;
    }
    Ok(())
}

fn write_string_union<'a>(
    out: &mut dyn Write,
    name: &str,
    values: impl Iterator<Item = &'a str>,
) -> std::io::Result<()> {
    let values = values.collect::<Vec<_>>();
    if values.is_empty() {
        writeln!(out, "export type {name} = never;\n")?;
        return Ok(());
    }

    writeln!(out, "export type {name} =")?;
    for value in values {
        writeln!(out, "  | {value:?}")?;
    }
    writeln!(out, ";\n")
}

fn write_nodes(out: &mut dyn Write, schema: &GraphSchema) -> std::io::Result<()> {
    writeln!(out, "  nodes: {{")?;
    for (kind, node) in schema.nodes() {
        writeln!(out, "    {kind:?}: {{")?;
        writeln!(out, "      properties: {{")?;
        for (property, spec) in &node.properties {
            writeln!(
                out,
                "        {property:?}: {{ required: {required} }},",
                required = spec.required
            )?;
        }
        writeln!(out, "      }},")?;
        writeln!(out, "    }},")?;
    }
    writeln!(out, "  }},")
}

fn write_relations(out: &mut dyn Write, schema: &GraphSchema) -> std::io::Result<()> {
    writeln!(out, "  relations: {{")?;
    for (name, relation) in schema.relations() {
        writeln!(out, "    {name:?}: {{")?;
        writeln!(out, "      from: {},", selector_ts(&relation.source))?;
        writeln!(out, "      to: {},", selector_ts(&relation.target))?;
        writeln!(
            out,
            "      cardinality: {cardinality:?},",
            cardinality =
                cardinality_name(relation.sources_per_target, relation.targets_per_source)
        )?;
        writeln!(
            out,
            "      retention: {retention:?},",
            retention = retention_name(relation.retention)
        )?;
        writeln!(out, "    }},")?;
    }
    writeln!(out, "  }},")
}

fn write_paths(out: &mut dyn Write, schema: &GraphSchema) -> std::io::Result<()> {
    writeln!(out, "  paths: {{")?;
    for (name, path) in schema.paths() {
        writeln!(out, "    {name:?}: {{")?;
        writeln!(out, "      from: {:?},", path.source)?;
        write!(out, "      path: [")?;
        for (index, relation) in path.path.iter().enumerate() {
            if index > 0 {
                write!(out, ", ")?;
            }
            write!(out, "{relation:?}")?;
        }
        writeln!(out, "],")?;
        writeln!(out, "      many: {:?},", path.many)?;
        writeln!(out, "    }},")?;
    }
    writeln!(out, "  }},")
}

fn write_property_types(out: &mut dyn Write, schema: &GraphSchema) -> std::io::Result<()> {
    writeln!(out, "export type PropertyKeyByKind = {{")?;
    for (kind, node) in schema.nodes() {
        write!(out, "  {kind:?}: ")?;
        if node.properties.is_empty() {
            writeln!(out, "never;")?;
        } else {
            let mut first = true;
            for property in node.properties.keys() {
                if !first {
                    write!(out, " | ")?;
                }
                first = false;
                write!(out, "{property:?}")?;
            }
            writeln!(out, ";")?;
        }
    }
    writeln!(out, "}};\n")?;
    writeln!(
        out,
        "export type PropertyKey = PropertyKeyByKind[NodeKind];\n"
    )
}

fn write_dbus_client(out: &mut dyn Write) -> std::io::Result<()> {
    out.write_all(include_str!("dbus_client.ts").as_bytes())
}

fn write_rx_adapter(out: &mut dyn Write, schema: &GraphSchema) -> std::io::Result<()> {
    out.write_all(include_str!("rx_adapter.ts").as_bytes())?;
    writeln!(
        out,
        "export class LocusObservableAdapter extends LocusObservableAdapterBase {{"
    )?;
    for (name, path) in schema.paths() {
        if path.many {
            continue;
        }

        let method = method_name(name);
        writeln!(
            out,
            "  {method}$(): Observable<OptionalNodeId> {{\n    return this.path$({name:?});\n  }}\n"
        )?;
        writeln!(
            out,
            "  {method}String$(): Observable<string> {{\n    return this.pathString$({name:?});\n  }}\n"
        )?;
        writeln!(
            out,
            "  {method}Property$(key: string): Observable<string> {{\n    return this.pathProperty$({name:?}, key);\n  }}\n"
        )?;
    }
    writeln!(out, "}}\n")?;
    writeln!(
        out,
        "export function createLocusObservables(client: LocusDbusClient = new LocusDbusClient()): LocusObservableAdapter {{\n  return new LocusObservableAdapter(client);\n}}\n\nexport const locus = createLocusObservables();\n"
    )
}

fn selector_ts(selector: &NodeSelector) -> String {
    match selector {
        NodeSelector::Any => "{ type: \"any\" }".to_string(),
        NodeSelector::Kind(kind) => format!("{{ type: \"kind\", kind: {kind:?} }}"),
        NodeSelector::Exact(id) => format!("{{ type: \"exact\", id: {id:?} }}"),
    }
}

fn method_name(name: &str) -> String {
    let mut output = String::new();
    let mut first = true;
    for part in name
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
    {
        let mut chars = part.chars();
        let Some(head) = chars.next() else {
            continue;
        };

        if first {
            output.push(head.to_ascii_lowercase());
        } else {
            output.push(head.to_ascii_uppercase());
        }
        output.extend(chars.map(|character| character.to_ascii_lowercase()));
        first = false;
    }

    if output
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_alphabetic() || character == '_')
    {
        output
    } else if output.is_empty() {
        "path".to_string()
    } else {
        format!("path{output}")
    }
}

fn cardinality_name(
    sources_per_target: Cardinality,
    targets_per_source: Cardinality,
) -> &'static str {
    match (sources_per_target, targets_per_source) {
        (Cardinality::One, Cardinality::One) => "one-to-one",
        (Cardinality::Many, Cardinality::One) => "many-to-one",
        (Cardinality::One, Cardinality::Many) => "one-to-many",
        (Cardinality::Many, Cardinality::Many) => "many-to-many",
    }
}

fn retention_name(retention: locus_schema::Retention) -> &'static str {
    match retention {
        locus_schema::Retention::Strong => "strong",
        locus_schema::Retention::Weak => "weak",
    }
}
